spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"  # Replace with your React app's origin
            allowedHeaders: "*"                     # Allows all headers
            allowedMethods:                         # Allows all HTTP methods
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
              - HEAD
